#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Mar 24 18:34:23 2012

import wx

# begin wxGlade: extracode
# end wxGlade



class About(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: About.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "PythonQuery", style=wx.ALIGN_CENTRE|wx.ST_NO_AUTORESIZE)
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("brokendish_iCON_Kuro.jpg", wx.BITMAP_TYPE_ANY))
        self.label_2 = wx.StaticText(self, -1, u"PythonQuery (作成中)\n\n2012　brokendish\n\nhttp://brokendish.org", style=wx.ALIGN_CENTRE)
        self.button_1 = wx.Button(self, -1, u"閉じる")

        self.__set_properties()
        self.__do_layout()

	#閉じるボタンのイベント
	self.Bind(wx.EVT_BUTTON, self.OnClose, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: About.__set_properties
        self.SetTitle("About")
        self.label_1.SetMinSize((282, 61))
        self.label_1.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: About.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, wx.BOTTOM|wx.EXPAND|wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add(self.bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

# end of class About
#閉じるボタンの処理
    def OnClose(self,event):
	        self.Close(True)

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = About(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
